Repository rakugoteam/Rakugo-Dialogue-System, pull requests merged in 2022-12, with the labels that each got.

#148 fix TestCharacter
  Test/TestParser/TestCharacter/TestCharacter.gd
Labels: bug

#158 Fix #155 #117 #116
  .gut_editor_config.json
  Test/TestParser/TestAsk/TestAsk.gd
  Test/TestParser/TestAsk/TestAsk.rk
  Test/TestParser/TestAsk/TestAsk.tscn
  Test/TestParser/TestMenu/TestMenu.gd
  Test/TestParser/TestMenu/TestMenu.rk
  Test/TestParser/TestMenu/TestMenu.tscn
  addons/Rakugo/Rakugo.gd
  addons/Rakugo/lib/systems/Parser.gd
Labels: majorChange

#161 add variable_changed signal
  addons/Rakugo/Rakugo.gd
Labels: majorChange

#160 wip #156
  addons/Rakugo/lib/systems/Parser.gd
Labels: inChangelog
