Repository rakugoteam/Rakugo-Dialogue-System, pull requests merged in 2023-01, with the labels that each got.

#165 Add variable_changed signals
  addons/Rakugo/Rakugo.gd
Labels: majorChange

#170 prepare to replace `character_exists()` by `has_character()`
  addons/Rakugo/Rakugo.gd
Labels: majorChange

#175 fix #168, set save_folder_path in _init
  addons/Rakugo/lib/systems/StoreManager.gd
Labels: inChangelog

#173 update #166 TestStartFromLabel
  Test/TestParser/TestStartFromLabel/TestStartFromLabel.gd
Labels: inChangelog

#176 fix#174 and #166, add RakugoTest class and update all parser tests
  Test/RakugoTest.gd
  Test/TestParser/TestAsk/TestAsk.gd
  Test/TestParser/TestCharacter/TestCharacter.gd
  Test/TestParser/TestFinish/TestFinish.gd
  Test/TestParser/TestJumpIf/TestJumpIf.gd
  Test/TestParser/TestMenu/TestMenu.gd
  Test/TestParser/TestParseAndExecute/TestParseAndExecute.gd
  Test/TestParser/TestSay/TestSay.gd
  Test/TestParser/TestStartFromLabel/TestStartFromLabel.gd
  Test/TestParser/TestStartFromLabel/TestStartFromLabel.rk
  Test/TestParser/TestVariables/TestVariables.gd
  Test/TestParser/TestVariables/TestVariables.rk
Labels: inChangelog

#164 fix#159 divide parser
  addons/Rakugo/Rakugo.gd
  addons/Rakugo/lib/systems/Executer.gd
  addons/Rakugo/lib/systems/Parser.gd
  addons/Rakugo/lib/systems/StoreManager.gd
  project.godot
Labels: inChangelog

#179 fix, now variable can be one letter long
  Test/TestParser/TestVariables/TestVariables.gd
  Test/TestParser/TestVariables/TestVariables.rk
  addons/Rakugo/lib/systems/Executer.gd
  addons/Rakugo/lib/systems/Parser.gd
Labels: inChangelog

#181 update, add exit keyword to rakuscript, it fix TestStartFromLabel too
  addons/Rakugo/lib/systems/Executer.gd
  addons/Rakugo/lib/systems/Parser.gd
Labels: inChangelog

#183 parser, add error when line is not handled. add tests. update test menu
  Test/TestParser/TestMenu/TestMenu.gd
  Test/TestParser/TestMenu/TestMenuChoiceParseFail.rk
  Test/TestParser/TestParseFail/TestParseFail.gd
  Test/TestParser/TestParseFail/TestParseFail.rk
  Test/TestParser/TestParseFail/TestParseFail.tscn
  addons/Rakugo/lib/systems/Parser.gd
Labels: majorChange

#186 Add Rakugo.stop_last_script
  .gut_editor_config.json
  .gutconfig.json
  Test/TestExecuter/TestStop/TestStop.gd
  Test/TestExecuter/TestStop/TestStop.rk
  Test/TestExecuter/TestStop/TestStop.tscn
  addons/Rakugo/Rakugo.gd
  addons/Rakugo/lib/systems/Executer.gd
Labels: majorChange

#194 Fix #190, update rakugo.has_variable
  addons/Rakugo/Rakugo.gd
Labels: majorChange

#193 Rakugo, get_character_variable push two errors
  addons/Rakugo/Rakugo.gd
Labels: bug

#191 Draft, Fix#88 save load thread
  Test/RakugoTest.gd
  Test/TestRakugo/TestSaveLoad/TestSaveLoad.gd
  Test/TestRakugo/TestSaveLoad/TestSaveLoad.rk
  addons/Rakugo/Rakugo.gd
  addons/Rakugo/lib/systems/Executer.gd
  addons/Rakugo/lib/systems/Parser.gd
  addons/Rakugo/lib/systems/StoreManager.gd
Labels: bug, majorChange

#195 fix #152 autoload Rakugo.gd
  addons/Rakugo/lib/systems/Executer.gd
  addons/Rakugo/lib/systems/Parser.gd
  addons/Rakugo/lib/systems/StoreManager.gd
  addons/Rakugo/plugin.gd
  project.godot
Labels: majorChange, inChangelog
