Repository rakugoteam/Rakugo-Dialogue-System, pull requests merged in 2023-10, with the labels that each got.

#254 fix #49 handle espace characters
  Test/TestExecuter/TestMenu/TestMenu.gd
  Test/TestParser/TestAsk/TestAsk.gd
  Test/TestParser/TestMenu/TestMenu.gd
  Test/TestParser/TestSay/TestSay.gd
  addons/Rakugo/lib/systems/Executer.gd
  addons/Rakugo/lib/systems/Parser.gd
Labels: bug

#258 hotfix for menu index out of range
  Test/TestExecuter/TestMenu/TestMenu.gd
  Test/TestExecuter/TestMenu/TestMenu.rk
  Test/TestParser/TestMenu/TestMenu.gd
  Test/TestParser/TestMenu/TestMenuChoiceParseFail.rk
  addons/Rakugo/lib/systems/Executer.gd
Labels: bug

#261 fix #257 use quotes in strings
  Test/TestExecuter/TestSay/TestSay.rk
  Test/TestParser/TestAsk/TestAsk.gd
  Test/TestParser/TestSay/TestSay.gd
  addons/Rakugo/lib/systems/Parser.gd
Labels: majorChange

#260 fix #259 remove warning in get_character
  addons/Rakugo/Rakugo.gd
Labels: inChangelog

#263 fix #262 Handle common operators for variable assignment
  Test/TestParser/TestVariables/TestVariables.gd
  Test/TestParser/TestVariables/TestVariables.rk
  addons/Rakugo/lib/systems/Executer.gd
  addons/Rakugo/lib/systems/Parser.gd
Labels: majorChange

#256 Fixes #255
  Test/TestExecuter/TestAsk/TestAsk.gd
  Test/TestExecuter/TestAsk/TestAsk.rk
  Test/TestExecuter/TestAsk/TestAsk.tscn
  Test/TestExecuter/TestMenu/TestMenu.gd
  Test/TestExecuter/TestMenu/TestMenu.tscn
  Test/TestExecuter/TestMenu/TestMenuChoiceVariable.rk
  Test/TestExecuter/TestSay/TestSay.tscn
  Test/TestParser/TestVariables/TestDynamicVars.rk
  Test/TestParser/TestVariables/TestVariables.gd
  Test/TestRakugo/TestVariablesRk/TestVariablesRk.gd
  addons/Rakugo/Rakugo.gd
  addons/Rakugo/lib/systems/Executer.gd
Labels: RakuScript, majorChange
